version: '3.0' 
 

services:
 angular: 
  build: ../agent-portal
  ports:
  - "4200:4200" 
 
 express: 
  build: ../messenger-backend
  ports:
  - "3000:3000" 
  links:
  - database 
 
 database: 
  image: mongo
  ports:
  - "27017:27017" 